# ZSH home setup
source ~/.config/zsh/home
# Theme
source ~/.config/zsh/theme
# Exports
source ~/.config/zsh/exports
# Plugins
source ~/.config/zsh/plugins
# Alias
source ~/.config/zsh/alias
# Conda
source ~/.config/zsh/conda
# Mise
source ~/.config/zsh/mise
# source it
source $ZSH/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
