# ZSH home setup
source ~/.config/zsh/home
# Theme
source ~/.config/zsh/theme
# Exports
source ~/.config/zsh/exports
# Plugins
source ~/.config/zsh/plugins
# Alias
source ~/.config/zsh/alias
# DIRENV for zsh
source ~/.config/zsh/direnv
# source it
source $ZSH/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/usr/local/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
        . "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    else
        export PATH="/usr/local/Caskroom/miniconda/base/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Load fabric
if [ -f "~/.config/fabric/fabric-bootstrap.inc" ]; then
  . "~/.config/fabric/fabric-bootstrap.inc"
fi
