tap "buildkite/buildkite"
tap "buildkite/cli"
tap "gcenx/wine"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "hpedrorodrigues/tools"
brew "jpeg-turbo"
brew "asdf"
brew "awscli"
brew "python@3.10"
brew "azure-cli"
brew "cabextract"
brew "circleci"
brew "cli53"
brew "glib"
brew "gnutls"
brew "colima"
brew "docker"
brew "exiftool", link: false
brew "gh"
brew "ghostscript"
brew "git"
brew "git-delta"
brew "git-flow", link: false
brew "git-flow-avh"
brew "gitleaks"
brew "gnupg"
brew "graphicsmagick"
brew "imagemagick", link: false
brew "libpq"
brew "mas"
brew "neovim"
brew "nghttp2"
brew "postgresql@14", restart_service: true
brew "redis", restart_service: true
brew "ripgrep"
brew "tmux"
brew "zsh"
brew "heroku/brew/heroku"
cask "1password-cli"
cask "android-sdk"
cask "android-studio"
cask "chromedriver"
cask "dockutil"
cask "font-hack-nerd-font"
cask "iterm2"
cask "postman"
cask "rectangle"
cask "smlnj"
cask "wine-crossover"
