tap "buildkite/buildkite"
tap "buildkite/cli"
tap "gcenx/wine"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/services"
tap "hpedrorodrigues/tools"
brew "jpeg-turbo"
brew "little-cms2"
brew "webp"
brew "jpeg-xl"
brew "aom"
brew "aws-sso-cli"
brew "awscli"
brew "azure-cli"
brew "glib"
brew "icu4c@76"
brew "harfbuzz"
brew "openjdk"
brew "bundletool"
brew "cabextract"
brew "circleci"
brew "cli53"
brew "cocoapods"
brew "docker"
brew "docker-compose"
brew "docker-credential-helper"
brew "dockutil"
brew "docutils"
brew "exiftool"
brew "fd"
brew "ffind"
brew "gh"
brew "openjpeg"
brew "ghostscript"
brew "git"
brew "git-delta"
brew "git-flow", link: false
brew "git-flow-avh"
brew "gitleaks"
brew "gnu-sed"
brew "gnutls"
brew "gnupg"
brew "libheif"
brew "graphicsmagick"
brew "libraw"
brew "imagemagick", link: false
brew "jq"
brew "lazygit"
brew "libpq"
brew "lima"
brew "mas"
brew "mise"
brew "neovim"
brew "nghttp2"
brew "ollama", restart_service: true
brew "pipx"
brew "pkgconf"
brew "podman"
brew "poetry"
brew "postgresql@16", link: true
brew "pure"
brew "python-setuptools"
brew "python@3.10"
brew "qemu"
brew "redis"
brew "ripgrep"
brew "tmux"
brew "tmuxp"
brew "w3m"
brew "wget"
brew "zsh"
brew "heroku/brew/heroku"
cask "1password"
cask "1password-cli"
cask "android-sdk"
cask "android-studio"
cask "chromedriver"
cask "dotnet-sdk"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "iterm2"
cask "miniconda"
cask "modern-csv"
cask "postman"
cask "rectangle"
cask "slack"
cask "smlnj"
cask "tableplus"
cask "tigervnc-viewer"
cask "visual-studio-code"
cask "wine-crossover"
cask "zed"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PowerDirector", id: 1556204761
mas "Transporter", id: 1450874784
mas "Xcode", id: 497799835
vscode "continue.continue"
vscode "dart-code.dart-code"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "jasonnutter.search-node-modules"
vscode "karunamurti.haml"
vscode "koichisasada.vscode-rdbg"
vscode "mechatroner.rainbow-csv"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "shopify.ruby-extensions-pack"
vscode "shopify.ruby-lsp"
vscode "sibiraj-s.vscode-scss-formatter"
vscode "vayan.haml"
