# ZSH home setup
source ~/.config/config/zsh/home
# Theme
source ~/.config/config/zsh/theme
# Exports
source ~/.config/config/zsh/exports
# Plugins
source ~/.config/config/zsh/plugins
# Alias
source ~/.config/config/zsh/alias
# DIRENV for zsh
source ~/.config/config/zsh/direnv
# source it
source $ZSH/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
